version: "2.1"

services:
  nocodb:
    depends_on:
      - root_db
    environment:
      NC_DB: "mysql2://noco:password@root_db:3306/root_db"
    image: "nocodb/nocodb:latest"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - nc_data:/usr/app/data

  root_db:
    environment:
      MYSQL_DATABASE: root_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: noco
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  nc_data:
